<?php
function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('encryption_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher/result'] = array(
        'title' => "Can you decipher the code?",
        'page callback' => 'cipher_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function encryption_form(){
    $form['shift']=array(
        '#title'=>'A number, please',
        '#type'=>'textfield',
        '#description'=>t('This number will be used to encrypt your word'),
        '#required'=>TRUE,
        '#element_validate'=>array(
            'element_validate_interger_positive',
        ),
    );
    $form['direction']=array(
        '#title'=>'Specify LEFT or RIGHT, please',
        '#type'=>'textfield',
        '#description'=>t('The direction will be used to encrypt your word'),
        '#required'=>TRUE,
        '#element_validate'=>array(
            'element_validate_direction',
        ),
    );
    $form['word']=array(
        '#title'=>'Input a word for encryption',
        '#type'=>'textfield',
        '#description'=>t('This word will be encrypted with the information you provided'),
        '#required'=>TRUE,
    );
    $form['submit']=array(
        '#type'=>'submit',
        '#value'=>'Submit',
    );
    return $form;
}

function element_validate_direction($element) {
    if(strtolower($element['#value']) == 'left' || strtolower($element['#value']) == 'right'){
        return;
    }else{
        form_error($element, t('Please specify either left or right'));
    }
}

function element_validate_interger_positive($element) {
    if($element['#value']<1){
        form_error($element, t('Please enter a positive interger'));
    }
}

function encryption_form_submit($form, &$form_state) {
    $form_state['redirect'] = 'cipher/result';
    $shift = $form_state['values']['shift'];
    $direction = $form_state['values']['direction'];
    $word = $form_state['values']['word'];
    var_dump($shift, $direction, $word);
    $_SESSION['values']=[$shift, $direction, $word];
    $form_state['redirect'] = 'cipher/result';
}

function cipher_result() {
    $show = '<h1>';
    foreach($_SESSION['values'] as $value){
        $show .= $value;
    }
    $show .= '</h1>';
    return $show;
}
